name: CI

on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: flake8 .
