name: CI

on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black
        run: |
          black --check . || ( \
            # If Black found formatting issues, auto-format the code and commit changes
            black . && \
            git config user.name "github-actions[bot]" && \
            git config user.email "github-actions[bot]@users.noreply.github.com" && \
            git add . && \
            git commit -m "Apply Black code formatting" && \
            git push \
          )

  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: pip install black

      - name: Run Flake8
        run: flake8 .