name: CI

on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"

permissions:
  contents: write

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort

      - name: Run isort
        run: isort .

  commit_changes:
    runs-on: ubuntu-latest
    needs: [style]
    steps:
      - uses: actions/checkout@v5
      - name: Commit changes (if any)
        run: |
          git diff --exit-code || (
            git config --global user.email "github-actions[bot]@users.noreply.github.com" && 
            git config --global user.name "github-actions[bot]" && 
            git commit -am "chore: apply linting, styling, formatting, and sort imports" &&
            git push
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
